compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

plugins:
    - path: .yarn/plugins/yarn-up-all-plugin.cjs
      spec: 'https://github.com/e5mode/yarn-up-all/releases/download/1.1.0/index.js'

yarnPath: .yarn/releases/yarn-4.12.0.cjs
